error_type: ValidationError
error_module: pydantic_core._pydantic_core
message: "1 validation error for ModelGeneratorOutputField\ndetails\n  Field required\
  \ [type=missing, input_value={'result': \"data={'integration': True}\"}, input_type=dict]\n\
  \    For further information visit https://errors.pydantic.dev/2.11/v/missing"
validation_errors:
- type: missing
  loc:
  - details
  msg: Field required
  input:
    result: 'data={''integration'': True}'
  url: https://errors.pydantic.dev/2.11/v/missing
