error_type: ValidationError
error_module: pydantic_core._pydantic_core
message: "2 validation errors for KafkaEventBusOutputState\nevent_id\n  Value error,\
  \ event_id must be a valid UUID string [type=value_error, input_value=None, input_type=NoneType]\n\
  \    For further information visit https://errors.pydantic.dev/2.11/v/value_error\n\
  timestamp\n  Value error, timestamp must be a valid ISO8601 string [type=value_error,\
  \ input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.11/v/value_error"
validation_errors:
- type: value_error
  loc:
  - event_id
  msg: Value error, event_id must be a valid UUID string
  input: null
  ctx:
    error:
      error_type: ValueError
      error_module: builtins
      message: event_id must be a valid UUID string
  url: https://errors.pydantic.dev/2.11/v/value_error
- type: value_error
  loc:
  - timestamp
  msg: Value error, timestamp must be a valid ISO8601 string
  input: null
  ctx:
    error:
      error_type: ValueError
      error_module: builtins
      message: timestamp must be a valid ISO8601 string
  url: https://errors.pydantic.dev/2.11/v/value_error
